### A Pluto.jl notebook ###
# v0.16.0

using Markdown
using InteractiveUtils

# ╔═╡ 54640fbe-86ce-42bf-89cd-6085fa2052cb
md"""
# Data collection and usefulness

The way data is collected is immensely impactful to how useful the data is subsequently. 

First, we need to differentiate between computerized data and computable data.

## PDF Files

### Scanned Documents

A scanned document stored as a PDF is computerized but it is not computable. From the computer's perspective it is simply a blob of pixels or more precisely an array of numbers between 0 and 255 that describe the brightness on the screen that we as humans read as letters, horizontal and vertical lines, letterhead, etc. As an example, consider this scanned document

![chemo worksheet](https://github.com/chapmanbe/raw-stuff/blob/main/DataSources/chemo_worksheet.png?raw=true)

I could potentially run an optical character recognition program to identiy text, but this is going to be a noisy (error prone) process that does not preserve an structure/context that may be implied in the original document. For example, running the OCR program [tesseract](https://github.com/tesseract-ocr/tesseract) on this document and then trying to copy the identified text yielded "mrieTorich" for "Antibiotics" on line 12. Recognizing the handwriting was hopeless.


### PDF generated by word processing software

## Text entry

Here is an excerpt from an actual note in my medical record:

```text
 PROBLEM:   HYPERTENSION
 
     1. CLINIC BP TODAY = 122/79  WITH GOAL BELOW 130/80
         
 
     2. CURRENT MEDICATION:  LISINOPRIL 10 MG DAILY
 
 
PROBLEM:  Chronic kidney disease DUE TO REMOVAL OF KIDNEY
 
     1. LAST CREATININE = 1.52 12/2018
           --HAVE BEEN STABLE FOR YEARS
         NORMAL MICROALBUMIN/CREATININE RATIO AND URINALYSIS
```

From a computational perspective, this string is an advance over the PDF-as-image data described previously. The computer recognizes `B` as a _B_ and `P` as a _P_ yet has no concept that `BP` represents blood pressure or that `122/79` represents the dual concepts 

- _systolic blood pressure: value=122, units of measurement=mmHg_
- _diastolic blood pressure: value=79, units of measurement=mmHg_

In order to make these values computable, a natural language processing program would have to be designed and implemented to recognize this, a process that would be imperfect at best, most likely imperfect and time consuming.

By contrast, below is an excerpt from the HL7 document containing the structured data entry for the blood pressure measurement taken during this visit. While hard to interpret by eye without knowing all the OID values used for HL7 documents, we can make the following observations about the observation:

1. The coding system that the data uses is clearly identified: (LOINC)
1. The concept is provided with its non-semantic ID (_"8480-6"_) as well as its text representation _"Systolic blood pressure"_
1. _"122"_ is identified as the value
1. _"mm[Hg]"_ is identified as the unit
1. Similar observations for the diastolic value

__These data are computable!__



```JSON
"component": [
                    {
                      "observation": {
                        "@classCode": "OBS",
                        "@moodCode": "EVN",
                        "templateId": [
                          {
                            "@root": "2.16.840.1.113883.10.20.22.4.27"
                          },
                          {
                            "@root": "2.16.840.1.113883.10.20.22.4.27",
                            "@extension": "2014-06-09"
                          }
                        ],
                        "id": {
                          "@root": "1.2.840.114350.1.13.90.2.7.1.2109.1",
                          "@extension": "5623842480-sysBP-22122"
                        },
                        "code": {
                          "@code": "8480-6",
                          "@codeSystem": "2.16.840.1.113883.6.1",
                          "@codeSystemName": "LOINC",
                          "originalText": "Systolic blood pressure"
                        },
                        "text": {
                          "reference": {
                            "@value": "#sysBP_5623842480"
                          }
                        },
                        "statusCode": {
                          "@code": "completed"
                        },
                        "effectiveTime": {
                          "@value": "20190318182800+0000"
                        },
                        "value": {
                          "@xsi:type": "PQ",
                          "@unit": "mm[Hg]",
                          "@value": "122",
                          "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance"
                        }
                      }
                    },
                    {
                      "observation": {
                        "@classCode": "OBS",
                        "@moodCode": "EVN",
                        "templateId": [
                          {
                            "@root": "2.16.840.1.113883.10.20.22.4.27"
                          },
                          {
                            "@root": "2.16.840.1.113883.10.20.22.4.27",
                            "@extension": "2014-06-09"
                          }
                        ],
                        "id": {
                          "@root": "1.2.840.114350.1.13.90.2.7.1.2109.1",
                          "@extension": "5623842480-diaBP-22122"
                        },
                        "code": {
                          "@code": "8462-4",
                          "@codeSystem": "2.16.840.1.113883.6.1",
                          "@codeSystemName": "LOINC",
                          "originalText": "Diastolic blood pressure"
                        },
                        "text": {
                          "reference": {
                            "@value": "#diaBP_5623842480"
                          }
                        },
                        "statusCode": {
                          "@code": "completed"
                        },
                        "effectiveTime": {
                          "@value": "20190318182800+0000"
                        },
                        "value": {
                          "@xsi:type": "PQ",
                          "@unit": "mm[Hg]",
                          "@value": "79",
                          "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance"
                        }
                      }
                    }
```

"""

# ╔═╡ 568ad495-ac20-40e3-9abb-220e5a0e1c78
md"""

## Drop down menus for data entry

Structured data is what we want, but simply because our data is structured and coded does not mean it is error free or immediately useful.

Consider this story that ran an ABC news 14 September 2021:

- [Indigenous vaccination rates in Victoria revised downwards after software error detected](https://www.abc.net.au/news/2021-09-14/indigenous-vaccination-rates-in-victoria-dashed-software-error/100459000)


- Data validation (range checking, format checking)
- data pulls vs manual entry (out of network data?)
- Patient-provided data
   - redunancy/data inconsistency/data entry errors
- URN
- Free text vs coded entry

"""

# ╔═╡ Cell order:
# ╟─54640fbe-86ce-42bf-89cd-6085fa2052cb
# ╟─568ad495-ac20-40e3-9abb-220e5a0e1c78
